apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zzm47nr7v-java-quarkus
  janus-idp.io/tekton: zzm47nr7v-java-quarkus
  backstage.io/kubernetes-id: zzm47nr7v-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zzm47nr7v-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
